### ISSUE TITLE
RuntimeError when transforming bme280 values

### ISSUE THREAD

**Issue by alanb128** [balena-labs-projects/sensor#16]
sensor  Transforming bme280 value(s)...
 sensor  Exception in thread Thread-1:
 sensor  Traceback (most recent call last):
 sensor    File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
 sensor      self.run()
 sensor    File "/usr/local/lib/python3.9/threading.py", line 892, in run
 sensor      self._target(*self._args, **self._kwargs)
 sensor    File "/usr/src/app/sensor.py", line 74, in background_web
 sensor      response = 'HTTP/1.0 200 OK\n\n'+ json.dumps(balenasense.sample())
 sensor    File "/usr/src/app/sensor.py", line 53, in sample
 sensor      return self.sensor.get_readings(self.context)
 sensor    File "/usr/src/app/reading.py", line 87, in get_readings
 sensor      x = reading.write_reading()
 sensor    File "/usr/src/app/reading.py", line 35, in write_reading
 sensor      new_fields = device_transform(dev.name, device_fields)
 sensor    File "/usr/src/app/transformers.py", line 20, in device_transform
 sensor      for field in fields:
 sensor  RuntimeError: dictionary keys changed during iteration

**Comment by alanb128** [comment]
This has been fixed.
